### ISSUE TITLE
Add all campus contact details in footer

### ISSUE THREAD

**Issue by eltazy** [KinshasaDigitalAcademy/kda-snoop-sourcing#168]
Right now the footer displays our email for contact and Kinshasa's phone number only. the other cities numbers and whatsapp should be added

### Sub-tasks
- [x] include an [sms shortcut](https://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link)
- [x] add whatsapp message link
- [x] add phone call link
- [x] filter or display per city

**Comment by lys-0243** [comment]
task already done
@eltazy
